### PR TITLE
Used F strings instead of format

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
# Pull Request Template

**title** -

write a short title for your pull request

**What have you Changed**

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I have added proper comments

Join Us on Discord:- https://discord.gg/JfbK3bS

## acknowledgement

- I have read and understood the above instructions. your pull request will be counted as open-source pull request and will be distributed under the MIT license.

### CODE REVIEW

**Review by codeperfectplus — COMMENTED** [review]
In the whole project the `format` was used, so changing the `F string` in one file doesn't make sense to me.

**Comment by kailashchoudhary11** [comment]
> In the whole project the `format` was used, so changing the `F string` in one file doesn't make sense to me.

well then, it should be changed in the whole project cause fstrings are much more faster than format.

**Comment by codeperfectplus** [comment]
> > In the whole project the `format` was used, so changing the `F string` in one file doesn't make sense to me.
> 
> well then, it should be changed in the whole project cause fstrings are much more faster than format.

yup,

**Comment by kailashchoudhary11** [comment]
Kindly merge this PR in the next PR I'll change it in all other files as well!

**Comment by codeperfectplus** [comment]
You can commit changes in this PR. No issue

**Pull request closed without merging**
